# These are the locations of your .spec files (descendants are searched too)
roots = ["ReplicatedStorage/Tests", "ServerScriptService/Tests"]

[extraOptions]
# Optionally, an extraOptions table can be passed to TestBootstrap